import Footer from "@/components/UI/Footer";
import Navbar from "@/components/UI/Navbar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Sans_Condensed } from "next/font/google";

const contentFont = IBM_Plex_Sans({
  variable: "--font-content",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const headingFont = IBM_Plex_Sans_Condensed({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${contentFont.variable} ${headingFont.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
